SELECT SEGMENT_NAME, TABLESPACE_NAME, BYTES, BLOCKS, EXTENTS
    FROM DBA_SEGMENTS
    WHERE SEGMENT_TYPE = 'INDEX'
    ORDER BY SEGMENT_NAME;
    
select TABLESPACE_NAME, 
       BLOCK_SIZE,  
       INITIAL_EXTENT,
       INITIAL_EXTENT/BLOCK_SIZE,
       EXTENT_MANAGEMENT,
       SEGMENT_SPACE_MANAGEMENT from SYS.DBA_TABLESPACES;
    
SELECT SEGMENT_NAME, SEGMENT_TYPE, TABLESPACE_NAME, EXTENT_ID, BYTES, BLOCKS
    FROM DBA_EXTENTS
    WHERE SEGMENT_TYPE = 'INDEX'
    ORDER BY SEGMENT_NAME;
    
    